export function buildShim(absoluteServerPath: string): string {
  const escaped = absoluteServerPath.replace(/\\/g, "/");
  return `// Generated by x64dbg-mcp service install
// Loads the real server entrypoint at: ${absoluteServerPath}
import("file:///${escaped}").catch((err) => {
  console.error("[x64dbg-mcp shim] Failed to load server:", err);
  process.exit(1);
});
`;
}
