import { pathToFileURL } from "node:url";

export function buildShim(absoluteServerPath: string): string {
  const fileUrl = pathToFileURL(absoluteServerPath).href;
  return `// Generated by x64dbg-mcp service install
// Loads the real server entrypoint at: ${absoluteServerPath}
import(${JSON.stringify(fileUrl)}).catch((err) => {
  console.error("[x64dbg-mcp shim] Failed to load server:", err);
  process.exit(1);
});
`;
}
